config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  resources :users, only: [:new, :create, :show]
  resources :events,  only: [:index, :new, :create, :show]
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :description,  presence: true
    belongs_to :creator, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.name = name.downcase }
    validates :name,  presence: true, length: { maximum: 50 }, uniqueness: true

    has_many :events, foreign_key: :creator_id, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all 
  end 

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = "Event created successfully!"
      redirect_to events_url
    else
      flash[:danger] = "Error creating this event!"
      render :new
    end
  end 

  private
  def event_params
    params.require(:event).permit(:description, :location, :date)
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @session = User.new
    end 

    def create
        if @user = User.find_by(name: params[:name].downcase)
            log_in @user
            flash[:success] = "Login Successful!"
            redirect_to @user
        else 
            flash[:danger] = 'You are not a member'
            render 'new'
        end 

    end 

    def destroy
        log_out
        redirect_to root_url
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user 
      flash[:success] = "Logged in successfully"
      redirect_to @user
    else
      flash.now[:danger] = "Account Creation Failed" 
      render 'new'
    end 
    
  end


  private
  def user_params
    params.require(:user).permit(:name)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
    end

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<h1>All events</h1>
<ul>
  <% @events.each do |event| %>
    <%= content_tag :li, event.description %>
  <% end %>
</ul>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= form_for @event do |f| %>
  <%= f.text_field :description, placeholder: "Enter Description" %><br>

  <%= f.submit 'Create Event' %>
<% end %>

app/views/events/show.html.erb
<h1> Event created by <%= @event.creator.name %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to 'Home', root_path %>
<% unless logged_in? %>
  <%= link_to 'Log in', login_path %>
<% else %>
  <%= link_to 'Profile', user_path(current_user) %>
  <%= link_to 'Create Event', new_event_path %>
  <%= link_to 'Log out', logout_path , :method => :delete %><br>
  <span>Logged in as: <%= current_user.name %></span>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.text_field :name, placeholder: "Enter your name" %>

  <%= f.submit 'Sign Up' %>
<% end %>

<p>Existing Member? <%= link_to 'Log in', login_path %></p>

app/views/users/show.html.erb
<h2><%= @user.name %> Events</h2>
<ul>
  <% @user.events.each do |event| %>
    <%= content_tag :li, event.description %>
  <% end %>
</ul>